name: Test
version: '${project.version}'
main: com.yuu.test.Test
api-version: 1.18

commands:
  message:
    description: メッセージを送信するコマンド
    aliases:
      - msg
  countdown:
    description: カウントダウンのコマンド
    aliases:
      - cnd